### ISSUE TITLE
why isn't this sync'd?

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-rostest#1]
I'm rebuilding due to errors trying to actually use ROS. I think it's due to the python3.8 stale libraries. I got an error that my local version (built from here) is newer than the new version (built via AUR for convenience).

Indeed, [AUR is on 1.12.14](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ros-melodic-rostest) and we're on 1.14.3 here.

I would love:

- a better way to incrementally push changes from here to AUR as soon as they are done. With hundreds of packages, I can't possibly keep track of what's updated/modified on AUR vs. not
- suggestions on how to always build locally and I'll just ignore AUR completely. I asked about this on my aur tool of choice, but haven't heard a recommendation yet.

**Comment by acxz** [comment]
I think if we can continuously see the output of the CI that @bionade24 is running, that would make our lives much better. We can tackle the issues that are specifically causing the packages to not sync.

EDIT: I wonder if there is a way to set up CI inside of each repo, like Travis or something. Travis CI is free as well, just setting it up for all the PKGBUILDs might be cumbersome.

**Comment by bionade24** [comment]
I thought about this, but free Travis is way too slow and afaik not API configurable. I also thought about getting everything into submodules and the use Gitlab CI on my own instance. But this would be overkill. Maybe Github's new CI has more resources and can be better configured than Travis?

**Comment by acxz** [comment]
@bionade24 I came across [`aurpublish`](https://github.com/eli-schwartz/aurpublish). I have started using it to maintain my own packages on the AUR. It may be a good idea.

**Comment by bionade24** [comment]
I'll look into it, thanks.
